kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "pca-manager-microservice.fullname" . }}-pca-manager-api
  labels:
    release: {{.Release.Name }}
    heritage: {{.Release.Service }}
    chart: {{ template "pca-manager-microservice.chart" . }}
data:
  config: |-
{{ .Files.Get "data/pca-manager-api-config.json" | indent 4 }}
